### ISSUE TITLE
Can this be used in a production app?

### ISSUE THREAD

**Issue by harrispoodle** [webrtc/FirebaseRTC#6]
Hello,

I am looking to integrate something like this into a website, as I currently use Firebase and this looks relatively simple. I'm quite new to WebRTC and I want to make sure that I am doing it correctly before releasing it. So would it be secure enough to be used in production?

Thanks in advance.

**Comment by ErikHellman** [comment]
Firebase (specifically Firestore) is used for signalling in this codelab and it should work fine for production use as well. Signalling in WebRTC is all about sending the information that WebRTC needs to connect to the other peers. Since this information can be sensitive from a security perspective, just make sure that you implement the rules in your Firestore database correctly.

**Comment by harrispoodle** [comment]
@ErikHellman Thanks.

I was also wondering if there was any option to be able to record the video chat?

**Comment by seansoawesome** [comment]
I was wondering the same thing too. Would there be a way to store the video in firestore?

**Comment by ErikHellman** [comment]
I suggest you all direct more general questions regarding WebRTC to https://webrtc.org/support/overview instead here. This repository is only for the codelab and is not meant to be used for production. Firebase can be used for signalling, but you still need to implement all that yourself. FEel free to use this as an inspiration though.
